use_frameworks!

platform :ios, '8.0'

target 'DeclarativeEngine_Example' do
  pod 'DeclarativeEngine', :path => '../'

  target 'DeclarativeEngine_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
