use_frameworks!

platform :ios, '8.0'

target 'declarative-engine_Example' do
  pod 'declarative-engine', :path => '../'

  target 'declarative-engine_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
